### ISSUE TITLE
Assembled, but ATF1508 or ATF1504 isn't detected.

### ISSUE THREAD

**Issue by Berzerkula** [roscopeco/atfprog-tools#1]
Greetings,

Acquired devices straight from Microchip/Atmel imported from their facility in Thailand and ```atfu``` is only attempting to use ATF1502.

Populated the PLCC84 with ATF1508AS-7JX84
Populated the PLCC44 with ATF1504AS-10JU44

I have no ATF1502 devices to test with.

Both aren't populated at the same time.

Any way to force the tool to select which ATF150x device to use?
The shrouded 5x2 connector is oriented with the silkscreen.

The Microchip ATDH1150USB connected won't read the ATF1504 or ATF1508. Is there a jumper on the PCB that needs to be shunted? Is JTAG-X only for the PLCC84 device?

Attaching the assembled PCB with ATF1508AS and 5V.
![ATF1508AS](https://github.com/roscopeco/atfprog-tools/assets/26439039/50218ce8-4b69-4b59-b39c-6cab4aaab51c)

![image](https://github.com/roscopeco/atfprog-tools/assets/26439039/2ff957f8-e091-4057-b860-67b744ea7aea)

Device is blank from factory as ATMISP shows. I installed into the T030 memory controller socket and attached the ATDH150USB to the  JTAG connector and blank checked. Device seems good.

![image](https://github.com/roscopeco/atfprog-tools/assets/26439039/95a2973d-0c17-4ecb-b69c-145b6bba5ce3)

Back side. I did resolder the USB-C connector shield at 4 points as it looked pretty weak.
![image](https://github.com/roscopeco/atfprog-tools/assets/26439039/c32b3f5f-68ea-40a4-b29e-17ad918cdf68)

**Comment by roscopeco** [comment]
Hello! 

Please pass `-d ATF1504` to select the device 🙂Currently we don’t do auto-detection of the chip.

**Comment by Berzerkula** [comment]
Ah, thank you @roscopeco   the elusive "-d" option!

![image](https://github.com/roscopeco/atfprog-tools/assets/26439039/fa7b6c8b-de4e-4ede-a293-60515ef3bd37)

**Comment by Berzerkula** [comment]
ATF1508, too! 
![image](https://github.com/roscopeco/atfprog-tools/assets/26439039/877d9480-2727-488a-8e98-a6cd8e32230c)

**Comment by Berzerkula** [comment]
Now I feel like a bonehead. I figured -h at top option would show me "-d"
I had to do -h after the command:

![image](https://github.com/roscopeco/atfprog-tools/assets/26439039/d7967a36-b0d4-48bf-9fdb-88af56ee98f1)

**Comment by Berzerkula** [comment]
Closing this ticket as all is working as designed. Didn't realize there was the -d option ( could have after digging more into the python script ). Thank you @roscopeco

**Comment by roscopeco** [comment]
No probs, thanks for the report, apologies it wasn’t clear. I will make sure this information is documented here on GitHub and in a sheet sent with the boards in future 🙂
